spring:
  jpa:
    show-sql: true
    properties:
       hibernate:
          format_sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
      path: /h2-ui

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: debug
      hibenate: debug